### ISSUE TITLE
[BUG] Youtube videos not loading

### ISSUE THREAD

**Issue by mansrm81** [Andrews54757/FastStream#329]
**Describe the bug**
Youtube videos don't load, just a spinning loading, I looked in the error tab and it says 403

**Version**
Latest version 1.3.40

**Platform**
Brave browser

**Steps to Reproduce**
Just try to watch any video.

**Comment by Laplaceeee** [comment]
update:
The same issue came back today.

previous:
I had the same issue with FastStream V1.3.39. By using FastStream V1.3.40, the problem is solved.

**Comment by mansrm81** [comment]
I was on 1.3.37 and had the problem and updated last night and it worked but now it doesn't work. lol

**Comment by Player505** [comment]
I am still experiencing the same bug on 1.3.40

**Comment by freezewind** [comment]
This issue fixexd by 1.3.40 on yesterday, but it happen again totday with 1.3.40.

**Comment by eeeeb** [comment]
I am having the same issue, videos are not loading with 1.3.40

**Comment by Andrews54757** [comment]
Google being google of course

**Comment by nightey89** [comment]
same here. neither 1.3.39 nor .40 worked.

**Comment by Andrews54757** [comment]
Fixed

**Comment by Laplaceeee** [comment]
Updated on Feb 6: it works with 1.3.41

Previous message:
The same problem persists with 1.3.41.

**Comment by lucasnoman** [comment]
On 1.3.41 it's still not working for me on Edge, nor Firefox.

**Comment by nightey89** [comment]
Me neither.

**Comment by mansrm81** [comment]
Doesn't work on Brave still.
