### ISSUE TITLE
[BUG] Youtube broken again

### ISSUE THREAD

**Issue by Andrews54757** [Andrews54757/FastStream#421]
We are aware that Youtube is broken for some people, as Google has changed their code again. This time, it's quite a drastic change and so it may take a while for Youtube.js and FastStream to be fixed.

Related bug reports:
- https://github.com/LuanRT/YouTube.js/issues/1043
- https://github.com/yt-dlp/yt-dlp/issues/14404

**Comment by Andrews54757** [comment]
We've released V1.3.61 as a temporary fix for Youtube. It will force FastStream to use the working client `0004de42` instead of the new broken one.

**Comment by audacieuxnumber1** [comment]
Hi, I'm not an expert, but since Google keeps changing youtube code again and again, I found these open-source tools that maybe might help fix future youtube problems : 


https://github.com/sebaro/ViewTube
http://sebaro.pro/viewtube/


https://viewtube.io/
https://uptime.viewtube.io/
https://github.com/ViewTube/viewtube


https://cobalt.tools/
https://github.com/imputnet/cobalt
https://x.com/imputnet
https://x.com/justusecobalt
https://meow.camera/viewer/#4258783365322591678
meow@imput.net

**Comment by chrieeax** [comment]
Figured I should post this here instead of starting a new bug thread,

I've been trying to use the new player for a few days now and it always stops playing after a short while.  I haven't been able to play a single video to completion with this new version.  It states there are lots of fragments that failed and clicking to retry doesn't help. 

Also I cannot download any videos at all, eventually a popup comes up stating "Failed to save video! Would you like to archive the player's buffer storage instead? - Drag and drop archive files on the player to load it" so there seems to be no way to stream or download in the current version.

I noticed in the new settings there is no way to swap between IOS/ANDROID/TV_EMBED/whatever the other option was, that would sometimes fix these kind of problems.  Is there an option I should be checking/unchecking or is this a more serious issue that requires another version update?

Using FastStream 1.3.61 with Firefox 143.0.1 on Windows 11 and it's literally any youtube video.

**Comment by Andrews54757** [comment]
Unfortunately this is a more serious issue, that error means that Google is almost finished rolling out their update. Google has started to disable players using their old code to download videos.

There no more option to switch clients because Google has started to enforce the same requirements for all clients: requiring a PoToken and using SABR.

People are working on a fix for but it will take time. Google tries very hard to make 3rd party clients difficult to make and its only getting harder.

**Comment by ale5000-git** [comment]
@Andrews54757
yt-dlp still works perfectly but YouTube now bind some data to video id: https://github.com/yt-dlp/yt-dlp/commit/bd5ed90419eea18adfb2f0d8efa9d22b2029119f

**Comment by Andrews54757** [comment]
We already use content PoTokens for subtitles and metadata. IIRC the actual video data is retrieved using session PoTokens only. I'll do some testing.

**Comment by ale5000-git** [comment]
> We already use content PoTokens for subtitles and metadata. IIRC the actual video data is retrieved using session PoTokens only. I'll do some testing.

I don't know this code in details so sorry if I misunderstood but it is possible that in the past a single PO Token was used for more than one video but now they need to be video specific (so bound to video id).

Quote from [here](https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide):
> Web Tokens for player (and subtitles) requests are bound to the video ID the associated /player request is for. YouTube has only recently started generating these for some clients (e.g. web).
> 
> As of writing, some clients, such as web_music use a session-bound PO Token for player requests. This is likely to change.
> 
> For Android (and presumably iOS), the Player PO Token is bound to the user session, similar to GVS tokens. If a Player PO token is provided, the GVS PO token is not required.

**Comment by Andrews54757** [comment]
I did some testing and you are right. Google is now requiring content bound PO tokens for video data. Will have to fix. Thanks!

**Comment by Andrews54757** [comment]
V1.3.62 should fix the issue.

**Comment by chrieeax** [comment]
Confirmed new version works perfectly.  Thanks for your efforts.

**Comment by sarudan** [comment]
On Firefox i get fragment errors, doesn't happen in Chrome.

<img width="858" height="152" alt="Image" src="https://github.com/user-attachments/assets/6a665f68-79ac-4b41-8d2c-594225c4a527" />

**Comment by Andrews54757** [comment]
Fixed in 1.3.63!

**Comment by demonkingzaine** [comment]
Unfortunately, Firefox still appears to be broken in regards to YouTube. I still get fragment errors in 1.3.63 upon attempting playback.

<img width="916" height="120" alt="Image" src="https://github.com/user-attachments/assets/74fc70a8-23d4-4206-ad3b-166bea292d94" />

Console contains a number of errors labeled "Error: No data from SABR UMP processor" and "No result from SABR UMP processor"

<img width="1538" height="208" alt="Image" src="https://github.com/user-attachments/assets/9a1aa02c-00bb-4900-a1e4-ea5f1d852cf5" />

**Comment by Andrews54757** [comment]
@demonkingzaine try clearing caches / reinstalling the extension.

**Comment by whodis1376** [comment]
> Fixed in 1.3.63!

Mine still show 1.3.62. I'm not too familiar with github but how do I update mine to 1.3.63?

**Comment by Brleegb11** [comment]
Give the fella a break ffs – it will break is not meant for YT?

**Comment by Brleegb11** [comment]
Depends on browser – FF seems to update or chrome just uninstall and drag into dev – easy save settings at bottom of page? Ask you get solution for this easy on reddit?
